version: '3.4'

services:
  gateway:
    container_name: reverseproxy
    image: alexandrejulien/peppermint-reverseproxy:latest
    ports:
      - "80:80"
  pet:
    container_name: pet
    image: ${DOCKER_REGISTRY-}pet
    build:
      context: .
      dockerfile: samples/DaprNBlocks.Samples.Pet.Api/Dockerfile
